const ScreenConst = {
  SIGNIN_SCREEN: 'SIGNIN_SCREEN',
  SIGNUP_SCREEN: 'SIGNUP_SCREEN',
  HOME_STACK: 'HOME',
  ORDER_STACK: 'CHATS',
  PROFILE_STACK: 'PROFILE',
  HOME_SCREEN: 'HOME_SCREEN',
  ORDER_SCREEN: 'ORDER_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  BOTTOM_TAB_FLOW: 'BOTTOM_TAB_FLOW',
  SERVICES_DETAIL: 'SERVICES_DETAIL',
  MAPS_SCREEN: 'MAPS_SCREEN',
  CHAT_DETAIL_SCREEN: 'CHAT_DETAIL_SCREEN',
  ADD_SERVICES: 'ADD_SERVICES',
  SIGNUP_MECHANIC_SCREEN: 'SIGNUP_MECHANIC_SCREEN',
  CONFIRMATION_SCREEN: 'CONFIRMATION_SCREEN',
  RATING_SCREEN: 'RATING_SCREEN',
};
export default ScreenConst;
